### ISSUE TITLE
require

### ISSUE THREAD

**Issue by daomengRen** [oo11o/imdber#1]
Hi, is it possible to support require to import this module, thanks

**Comment by oo11o** [comment]
I will solve this problem this month

**Comment by oo11o** [comment]
> Hi, is it possible to support require to import this module, thanks

I will solve this problem this month

**Comment by oo11o** [comment]
Hello. Fixed

**Comment by daomengRen** [comment]
TypeError: imdb.getYear is not a function,looking forward to your fix, thanks
