### ISSUE TITLE
start('tt0064624')

### ISSUE THREAD

**Issue by daomengRen** [oo11o/imdber#3]
When I execute "start('tt0064624')", the following error will appear, I don't know what went wrong,thank you
```
/root/node_modules/imdber/src/Parse.js:52
      runtime: item.node.runtime.seconds,
                                 ^
TypeError: Cannot read property 'seconds' of null
```

**Comment by oo11o** [comment]
Hi. Could you send me your code?

**Comment by oo11o** [comment]
Fixed. Similars movie of tt0064624  (https://www.imdb.com/title/tt14478264) doesn't have movie time.

**Comment by daomengRen** [comment]
(https://www.imdb.com/title/tt0064624/)  this movie

**Comment by oo11o** [comment]
> (https://www.imdb.com/title/tt0064624/) this movie

Yes. This movie (https://www.imdb.com/title/tt0064624/) has a similar movie (https://www.imdb.com/title/tt14478264) which caused the error because doesn't have movie time

**Comment by daomengRen** [comment]
can that fix the situation

**Comment by daomengRen** [comment]
If the situation with similar movies is more complicated, can it be configured to ignore these similar movies

**Comment by oo11o** [comment]
> If the situation with similar movies is more complicated, can it be configured to ignore these similar movies

I fixed. Try update package
`
{
  id: 'tt0064624',
  title: 'Maid in Sweden',
  description: "Schoolgirl Inga goes to visit her sister in Stockholm and is shocked to find her living with her boyfriend, Casten. She succumbs to Casten's charms, and after having broken up her sister's love affair, returns home to her parents.",
  year: 1971,
  image: 'https://m.media-amazon.com/images/M/MV5BNjMwYTAwM2UtMzRkNy00MzllLTg5OTMtNTExZjMwNzc0ZmQwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  time: 4800,
  rating: { imdb: 4.3, vote: 1363, metacritic: undefined },
  genres: [ 'Drama' ],
  countries: [ { id: 'SE', text: 'Sweden' }, { id: 'US', text: 'United States' } ],
  actors: [
`

**Comment by daomengRen** [comment]
thanks

**Comment by oo11o** [comment]
> If the situation with similar movies is more complicated, can it be configured to ignore these similar movies

This is a greater idea about configuration. I think that I will do it.  A similar situation is ignored now.

**Comment by daomengRen** [comment]
ok,got it

**Comment by daomengRen** [comment]
> > 如果类似电影的情况比较复杂，是否可以配置忽略这些类似电影
> 
> 这是关于配置的一个更好的想法。我想我会做到的。类似的情况现在被忽略了。

I suddenly thought, if I can configure the output items, whether I can reduce the time to get the data, at present, it takes a long time for me to get the data once, I want to reduce the time appropriately, I don't know how to do it

**Comment by oo11o** [comment]
The time depends on many factors, especially the IMDb site. The beginning goes to connect to IMDb, like in a browser, wait for a response, and return the data. 

For instant speed, need to develop and deploy Rest API, this will reduce the response speed many times. 

I thought to deploy such a service. But if you need it now, you can find similar REST API

**Comment by daomengRen** [comment]
So can I configure the output item?

**Comment by oo11o** [comment]
> So can I configure the output item?

Not at the moment. I need a lot of free time for this, which I don't have right now

**Comment by daomengRen** [comment]
ok,i look forward to

**Comment by oo11o** [comment]
> So can I configure the output item?

Perhaps the following methods will help you

imdb.getTitle()  - string | return title of movie
imdb.getYear() - string |return year of movie
imdb.getDescription() - string | return description of movie
imdb.getGenres() - array | return genres of movie
